# Week 1: MSE and R^2, Accuracy and Error, Precision and Recall

#### Making Meaningful Predictions from Data
This week we were introduced to three sets of concepts. We looked at MSE and R^2 along with their relation to one another. We learned about how to measure Accuracy and Error mathematically. And finally we learned about Precision and Recall using true/false positive/negatives.

## Part 1: MSE and R^2

We are going to work with a 2D example of these topics for the purpose of visualization. In your capstone project at the end of this series you will use this on your dataset as a whole. This example is meant to be simpler as an introduction to the topics.

In [1]:
import numpy as np
from sklearn import linear_model

### The "Data"

In this example we are going to use a 2D numpy array to calculate two separate MSE and R^2 values. The array defined below will be the "data" for this example.

###### Note: Because of this exmaple using numpy arrays, most of our answers will return in an array form. Don't worry! This isn't affecting any of our answers! 

In [2]:
model = linear_model.LinearRegression()
exArray = np.array([[0], [1], [3], [2],
                   [2],[3],[4], [0]])

In [3]:
print(exArray.shape) #Check the dimanesions of exArray using numpy operators 
#if you are unfamiliar with this don't worry it is just for this example

exArray[0]

(8, 1)


array([0])

In [4]:
#Note that X and y must have the same dimensions!
y = exArray[4:]
X = exArray[:4]

In [5]:
#We have to fit (train) our model!
model.fit(X,y)
# Theta would be the coef_
print('Coefficient: \n', model.coef_)

Coefficient: 
 [[0.3]]


In [6]:
#The values of these test arrays are unimportant, so the values listed here are random.
#Try changing them around and running through the below code again to see how they affect MSE and R^2

# Original values for the example
XTest = np.array([[-2]])
yTest = np.array([[4]])

In [7]:
# We predict the y1
predictions = model.predict(XTest)
predictions

array([[1.2]])

In [8]:
#TODO Calculate the squared differences as in lecture.
differences = [(x-y)**2 for (x,y) in zip(predictions, y)]

In [9]:
differences

[array([0.64])]

The MSE is just the average (Mean) of these squared differences:

In [10]:
#TODO Calculate the MSE
MSE = sum(differences)/len(differences)
print("MSE = " + str(MSE)) #Answer should be .64

MSE = [0.64]


And the **Mean Absolute Error** would be:

In [11]:
MAE = np.mean([abs(x-y) for (x,y) in zip(predictions, y)])
print("MAE = " + str(MAE))

MAE = 0.8000000000000003


As we saw in the lectures, the R^2 (and the FVU, or "Fraction of Variance Unexplained") normalize the Mean Squared Error based on the variance of the data:

In [12]:
#TODO Calculate R2
FVU = MSE / np.var(y)

#SOLN (there are more ways than this to solve this)
R2 = 1 - FVU

print("R2 = " + str(R2)) #Answer should be roughly .707...

R2 = [0.70742857]



**Another example of MSE**  
You can use any list below  
a = actual list  
p = predicted list

The results should be:  
MSE 1 = 8340.546666666667  
MSE 2 = 5

In [13]:
a = [1, 21, 5, 7, 3.2, 4.2]
p = [1, 222, 55, 77, 33, 41]

#a = [4, 3, 2, 1]
#p = [1, 2, 3, 4]

def MSE(pred, actual):
    dif = [(x-y)**2 for (x,y) in zip (p, a)]
    return sum(dif)/len(dif)
   
MSE(p, a)

8340.546666666667

## Part 2: Accuracy and Error

To start measuring accuracy and error, we must first replace our output variable with a binary variable indicating if the value in the array is greater than a select value. For this example we will check if the values are greater than or equal to 2.

In [14]:
y_class = [(num >= 2) for num in y]
modelA = linear_model.LogisticRegression()
modelA.fit(X, y_class)
y_class

/home/alcides/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


[array([ True]), array([ True]), array([ True]), array([False])]

In [15]:
predictionsA = modelA.predict(X)

In [16]:
correct = predictionsA == y_class
correct

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False, False, False, False]])

### Classification Diagnostics: Accuracy

In [17]:
#TODO Calculate Accuracy in any way not involving TP, TF, FP, FN

accuracy = sum(correct)/len(predictionsA)
print("Accuracy = " + str(accuracy[0])) #Answer should be .75

Accuracy = 0.75


In [18]:
TP = sum([(p and l) for (p,l) in zip(predictionsA, y_class)])
FP = sum([(p and not l) for (p,l) in zip(predictionsA, y_class)])
TN = sum([(not p and not l) for (p,l) in zip(predictionsA, y_class)])
FN = sum([(not p and l) for (p,l) in zip(predictionsA, y_class)])

In [19]:
print("TP = " + str(TP))
print("FP = " + str(FP))
print("TN = " + str(TN))
print("FN = " + str(FN))

TP = [3]
FP = 1
TN = 0
FN = 0


In [20]:
#TODO Show that calculating accuracy using true/false positives/negatives will get the same answer

TFAccuracy = (TP + TN) / (TP + TN + FP + FN)
TFAccuracy[0]

0.75

In [21]:
TPR = TP / (TP + FN)
TNR = TN / (TN + FP)
print(TPR[0], TNR)

1.0 0.0


In [22]:
BER = 1 - 1/2 * (TPR + TNR)
print("Balanced error rate = " + str(BER)) #Answer should be .5

Balanced error rate = [0.5]


## Part 3: Precision and Recall

Precision and Recall are often used to rank performance of models. These can both be defined in terms of True Positives, False Positives, and False Negatives. (Though knowing any three of these true/false positives/negatives will give you the number of the remaining term)

In [23]:
#TODO Calculate Precision and recall in the terms defined in lecture.

precision = TP / (TP + FP)
recall = TP / (TP + FN)

precision, recall #Answers should be (.75, 1.0)

(array([0.75]), array([1.]))

The F1 score is just the average (precisely, the harmonic mean) of precision and recall. This is useful since it's easy to have either a good precision, or a good recall in isolation, but it's hard for both values to be high simultaneously.

In [24]:
F1 = 2 * (precision*recall) / (precision + recall)
F1 #Answer should be roughly .857...

array([0.85714286])

## You're All Done!

We have now introduced some basic ideas of classification and ranking. Next week you will use them on a dataset of reviews and see how these ideas can be applied to a proper dataset!